### ISSUE TITLE
Select two opensource repos for the next round of analysis

### ISSUE THREAD

**Issue by bcdasilv** [bcdasilv/pull-request-analysis#1]
Tanay suggested looking at this list as a starting point: [awesome projects for beginners](https://github.com/MunGell/awesome-for-beginners)

Post your suggestions down here in this thread. Pre-select 3 and I'll give my opinion.

**Comment by tanayg** [comment]
Here are the three that I think we should pick and the reasons why.

1. https://github.com/phpmyadmin/phpmyadmin. I like this one a lot because it has been around for more than 20 years and it still has active contributors. It's massive codebase with more than 100,000 commits. We might need to limit the number of pull requests by the date or some other other metric. In addition, it is probably the most popular open source PHP project that is still used today.
2. https://github.com/eslint/eslint. This is a widely used (~50m users) linter for javascript projects. The project is still quite active and their contribution guidelines are among the best that I have seen. The reviewers also seem fairly active on the repo.
3. https://github.com/hexojs/hexo. This is a blog framework written in NodeJS. They have very thorough contribution guidelines and a very active group of contributors. They also talk a lot in the comments section of the pull requests.

I tried to get a good variance of languages, project sizes, and project types. Let me know what you think!

**Comment by bcdasilv** [comment]
I vote for eslint and hexo. Eslint has a very detailed documentation on how to contribute while hexo doesn't have the same and it's smaller (apparently). That would be interesting to compare rejection reasons from both.

**Comment by siriwans** [comment]
I'm good with either of those. They both look good to me.

**Comment by tanayg** [comment]
Looks like we're starting with ESLint and Hexo!
